#!/bin/bash

# Quick Deploy Script for Wizard Backend on EC2
# This script automates the entire deployment process

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration (update these!)
GITHUB_REPO="https://github.com/YOUR_USERNAME/wizard-backend.git"
DOMAIN=""
EMAIL=""
JWT_SECRET=""
CONTRACT_PRIVATE_KEY=""
AWS_ACCESS_KEY=""
AWS_SECRET_KEY=""
S3_BUCKET=""

# Functions
print_header() {
    echo ""
    echo -e "${CYAN}================================================${NC}"
    echo -e "${CYAN}   $1${NC}"
    echo -e "${CYAN}================================================${NC}"
    echo ""
}

print_info() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC}  $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_step() {
    echo ""
    echo -e "${BLUE}▶${NC} $1"
}

# Check if running on EC2
check_ec2() {
    if [ ! -f /sys/hypervisor/uuid ] || [ $(head -c 3 /sys/hypervisor/uuid) != "ec2" ]; then
        print_warning "This doesn't appear to be an EC2 instance"
        read -p "Continue anyway? (y/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
}

# Prompt for configuration if not set
prompt_config() {
    if [ -z "$GITHUB_REPO" ]; then
        read -p "Enter your GitHub repository URL: " GITHUB_REPO
    fi
    
    if [ -z "$DOMAIN" ]; then
        read -p "Enter your domain (e.g., wizard.example.com): " DOMAIN
    fi
    
    if [ -z "$EMAIL" ]; then
        read -p "Enter your email for SSL certificates: " EMAIL
    fi
    
    if [ -z "$JWT_SECRET" ]; then
        JWT_SECRET=$(openssl rand -hex 32)
        print_info "Generated JWT secret"
    fi
    
    if [ -z "$CONTRACT_PRIVATE_KEY" ]; then
        read -s -p "Enter contract deployment private key: " CONTRACT_PRIVATE_KEY
        echo
    fi
    
    if [ -z "$AWS_ACCESS_KEY" ]; then
        read -p "Enter AWS Access Key ID (for S3 backups): " AWS_ACCESS_KEY
    fi
    
    if [ -z "$AWS_SECRET_KEY" ]; then
        read -s -p "Enter AWS Secret Access Key: " AWS_SECRET_KEY
        echo
    fi
    
    if [ -z "$S3_BUCKET" ]; then
        read -p "Enter S3 bucket name for backups: " S3_BUCKET
    fi
}

# Main deployment process
main() {
    print_header "Wizard Backend Quick Deploy"
    
    # Check if root
    if [ "$EUID" -ne 0 ]; then 
        print_error "Please run as root (use sudo)"
        exit 1
    fi
    
    check_ec2
    prompt_config
    
    print_header "Starting Deployment"
    
    # Step 1: System Update
    print_step "Updating system packages..."
    apt-get update -qq
    apt-get upgrade -y -qq
    print_info "System updated"
    
    # Step 2: Install dependencies
    print_step "Installing dependencies..."
    apt-get install -y -qq git curl wget vim htop iotop ncdu net-tools \
        software-properties-common apt-transport-https ca-certificates \
        gnupg lsb-release ufw fail2ban unattended-upgrades
    print_info "Dependencies installed"
    
    # Step 3: Clone repository
    print_step "Cloning repository..."
    cd /tmp
    rm -rf wizard-backend
    git clone $GITHUB_REPO wizard-backend
    cd wizard-backend/backend
    chmod +x scripts/*.sh
    print_info "Repository cloned"
    
    # Step 4: Run deployment script
    print_step "Running deployment script..."
    ./scripts/deploy-ec2.sh
    print_info "Base deployment complete"
    
    # Step 5: Setup storage
    print_step "Setting up storage..."
    ./scripts/setup-ec2-storage.sh
    print_info "Storage configured"
    
    # Step 6: Configure environment
    print_step "Configuring environment..."
    cat > /opt/wizard-app/.env.production << EOF
# Auto-generated by quick-deploy.sh
HOST=0.0.0.0
PORT=8080
RUST_LOG=info
NODE_ENV=production

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=86400

SUPERPOSITION_RPC_URL=https://testnet-rpc.superposition.so
SUPERPOSITION_CHAIN_ID=98985
SUPERPOSITION_EXPLORER_URL=https://testnet-explorer.superposition.so
CONTRACT_PRIVATE_KEY=${CONTRACT_PRIVATE_KEY}

STORAGE_PATH=/app/storage
MAX_FILE_SIZE=10485760
MAX_PROJECT_SIZE=52428800

ALLOWED_ORIGINS=https://${DOMAIN}

RATE_LIMIT_PER_MINUTE=60
RATE_LIMIT_PER_HOUR=1000

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
AWS_REGION=us-east-1
S3_BACKUP_BUCKET=${S3_BUCKET}

DOMAIN=${DOMAIN}
EMAIL=${EMAIL}
API_URL=https://${DOMAIN}/api
FRONTEND_URL=https://${DOMAIN}

DEBUG_MODE=false
VERBOSE_ERRORS=false
EOF
    chmod 600 /opt/wizard-app/.env.production
    print_info "Environment configured"
    
    # Step 7: Copy application files
    print_step "Copying application files..."
    cp docker-compose.production.yml /opt/wizard-app/
    cp Dockerfile.production /opt/wizard-app/
    cp Dockerfile.compiler /opt/wizard-app/
    cp -r nginx /opt/wizard-app/
    cp -r src /opt/wizard-app/
    cp Cargo.* /opt/wizard-app/
    print_info "Application files copied"
    
    # Step 8: Build Docker images
    print_step "Building Docker images..."
    cd /opt/wizard-app
    docker-compose -f docker-compose.production.yml build
    print_info "Docker images built"
    
    # Step 9: Start services (without SSL first)
    print_step "Starting services..."
    docker-compose -f docker-compose.production.yml up -d
    sleep 10
    print_info "Services started"
    
    # Step 10: Setup SSL
    print_step "Setting up SSL certificates..."
    cd /tmp/wizard-backend/backend
    ./scripts/setup-ssl.sh $DOMAIN $EMAIL
    print_info "SSL certificates configured"
    
    # Step 11: Restart with SSL
    print_step "Restarting services with SSL..."
    cd /opt/wizard-app
    docker-compose -f docker-compose.production.yml restart nginx
    print_info "Services restarted with SSL"
    
    # Step 12: Create admin user
    print_step "Creating admin user..."
    echo ""
    echo "Enter admin credentials:"
    read -p "Admin email: " ADMIN_EMAIL
    read -s -p "Admin password (min 8 chars): " ADMIN_PASSWORD
    echo ""
    
    cd /tmp/wizard-backend/backend
    ./scripts/init-admin.sh --email "$ADMIN_EMAIL" --password "$ADMIN_PASSWORD"
    print_info "Admin user created"
    
    # Step 13: Setup monitoring
    print_step "Setting up monitoring..."
    cd /opt/wizard-app
    nohup ./scripts/resource-monitor.sh > /opt/wizard-data/logs/monitor.log 2>&1 &
    print_info "Monitoring started"
    
    # Step 14: Configure firewall
    print_step "Configuring firewall..."
    ufw --force enable
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow ssh
    ufw allow 80/tcp
    ufw allow 443/tcp
    print_info "Firewall configured"
    
    # Step 15: Verify deployment
    print_header "Verifying Deployment"
    
    # Check health
    if curl -f -s -o /dev/null -w "%{http_code}" https://${DOMAIN}/health | grep -q "200"; then
        print_info "Health check: PASSED"
    else
        print_warning "Health check: FAILED (may need more time)"
    fi
    
    # Check SSL
    if curl -f -s -o /dev/null -w "%{http_code}" https://${DOMAIN} | grep -q "200\|301\|302"; then
        print_info "SSL check: PASSED"
    else
        print_warning "SSL check: FAILED (check DNS)"
    fi
    
    # Check services
    RUNNING=$(docker ps --format "table {{.Names}}\t{{.Status}}" | grep -c "Up")
    print_info "Services running: $RUNNING"
    
    # Display summary
    print_header "Deployment Complete!"
    
    echo -e "${GREEN}✅ Your Wizard Backend is deployed!${NC}"
    echo ""
    echo "Access your application at:"
    echo -e "  ${CYAN}https://${DOMAIN}${NC}"
    echo ""
    echo "Important information:"
    echo "  • Admin token saved to: /tmp/.admin-token"
    echo "  • Environment config: /opt/wizard-app/.env.production"
    echo "  • Logs: /opt/wizard-data/logs/"
    echo "  • Backups: /opt/wizard-data/backups/"
    echo ""
    echo "Useful commands:"
    echo "  • View logs: /opt/wizard-app/logs.sh"
    echo "  • Check status: /opt/wizard-app/status.sh"
    echo "  • Restart: /opt/wizard-app/restart.sh"
    echo "  • Backup: /opt/wizard-app/scripts/backup.sh"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Test authentication endpoints"
    echo "  2. Configure CloudWatch monitoring"
    echo "  3. Set up S3 backup automation"
    echo "  4. Test the application thoroughly"
    echo ""
    
    # Save deployment info
    cat > /opt/wizard-app/deployment-info.txt << EOF
Deployment Information
======================
Date: $(date)
Domain: https://${DOMAIN}
Instance: $(ec2-metadata --instance-id 2>/dev/null || echo "N/A")
IP: $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "N/A")
Region: $(ec2-metadata --availability-zone 2>/dev/null || echo "N/A")

Services Status:
$(docker ps --format "table {{.Names}}\t{{.Status}}")

Disk Usage:
$(df -h /opt/wizard-data)

Memory Usage:
$(free -h)
EOF
    
    print_info "Deployment info saved to /opt/wizard-app/deployment-info.txt"
    
    print_header "Deployment Successful! 🎉"
}

# Run main function
main "$@"