#!/bin/bash

# SSL Setup Script for Wizard Backend
# Automatically configures SSL certificates using Let's Encrypt

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
DOMAIN=${1:-""}
EMAIL=${2:-""}
STAGING=${3:-"false"}
WIZARD_APP_DIR="/opt/wizard-app"
NGINX_SSL_DIR="${WIZARD_APP_DIR}/nginx/ssl"

# Functions
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# Usage function
usage() {
    echo "SSL Setup Script for Wizard Backend"
    echo ""
    echo "Usage: $0 <domain> <email> [staging]"
    echo ""
    echo "Arguments:"
    echo "  domain   - Your domain name (e.g., wizard.example.com)"
    echo "  email    - Email for Let's Encrypt notifications"
    echo "  staging  - Use staging server for testing (true/false, default: false)"
    echo ""
    echo "Examples:"
    echo "  $0 wizard.example.com admin@example.com"
    echo "  $0 wizard.example.com admin@example.com true  # For testing"
    exit 1
}

# Check arguments
if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
    print_error "Missing required arguments"
    usage
fi

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    print_error "Please run this script as root (use sudo)"
    exit 1
fi

echo "================================================"
echo "   SSL Setup for ${DOMAIN}"
echo "================================================"
echo ""

# Step 1: Install Certbot
print_step "Installing Certbot..."
if ! command -v certbot &> /dev/null; then
    apt-get update
    apt-get install -y certbot python3-certbot-nginx
    print_info "Certbot installed"
else
    print_info "Certbot already installed"
fi

# Step 2: Stop services temporarily
print_step "Stopping services temporarily..."
if [ -f "${WIZARD_APP_DIR}/stop.sh" ]; then
    ${WIZARD_APP_DIR}/stop.sh
else
    docker-compose -f ${WIZARD_APP_DIR}/docker-compose.production.yml down 2>/dev/null || true
fi

# Step 3: Obtain SSL certificate
print_step "Obtaining SSL certificate for ${DOMAIN}..."

CERTBOT_ARGS="certonly --standalone -d ${DOMAIN} --email ${EMAIL} --agree-tos --non-interactive"

if [ "$STAGING" == "true" ]; then
    print_warning "Using Let's Encrypt STAGING server (for testing)"
    CERTBOT_ARGS="${CERTBOT_ARGS} --staging"
fi

if certbot ${CERTBOT_ARGS}; then
    print_info "SSL certificate obtained successfully"
else
    print_error "Failed to obtain SSL certificate"
    exit 1
fi

# Step 4: Create SSL directory
print_step "Setting up SSL directory..."
mkdir -p ${NGINX_SSL_DIR}
chmod 755 ${NGINX_SSL_DIR}

# Step 5: Copy certificates
print_step "Copying certificates..."
if [ "$STAGING" == "true" ]; then
    CERT_PATH="/etc/letsencrypt/live/${DOMAIN}-0001"
else
    CERT_PATH="/etc/letsencrypt/live/${DOMAIN}"
fi

if [ -d "$CERT_PATH" ]; then
    cp ${CERT_PATH}/fullchain.pem ${NGINX_SSL_DIR}/
    cp ${CERT_PATH}/privkey.pem ${NGINX_SSL_DIR}/
    cp ${CERT_PATH}/chain.pem ${NGINX_SSL_DIR}/ 2>/dev/null || true
    
    # Set proper permissions
    chmod 644 ${NGINX_SSL_DIR}/fullchain.pem
    chmod 600 ${NGINX_SSL_DIR}/privkey.pem
    
    print_info "Certificates copied to ${NGINX_SSL_DIR}"
else
    print_error "Certificate directory not found: ${CERT_PATH}"
    exit 1
fi

# Step 6: Generate DH parameters for extra security
print_step "Generating DH parameters (this may take a few minutes)..."
if [ ! -f ${NGINX_SSL_DIR}/dhparam.pem ]; then
    openssl dhparam -out ${NGINX_SSL_DIR}/dhparam.pem 2048
    chmod 644 ${NGINX_SSL_DIR}/dhparam.pem
    print_info "DH parameters generated"
else
    print_info "DH parameters already exist"
fi

# Step 7: Update nginx configuration
print_step "Updating nginx configuration..."
if [ ! -f ${WIZARD_APP_DIR}/nginx/nginx.conf.bak ]; then
    cp ${WIZARD_APP_DIR}/nginx/nginx.conf ${WIZARD_APP_DIR}/nginx/nginx.conf.bak
fi

# Create SSL-enabled nginx config
cat > ${WIZARD_APP_DIR}/nginx/nginx-ssl.conf << 'EOF'
# This file is auto-generated by setup-ssl.sh
# SSL configuration snippet for nginx

# SSL Configuration
ssl_certificate /etc/nginx/ssl/fullchain.pem;
ssl_certificate_key /etc/nginx/ssl/privkey.pem;
ssl_trusted_certificate /etc/nginx/ssl/chain.pem;

# SSL Session
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

# DH Parameters
ssl_dhparam /etc/nginx/ssl/dhparam.pem;

# Protocols and Ciphers
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;

# Security Headers
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
EOF

# Update domain in nginx config
sed -i "s/server_name _;/server_name ${DOMAIN};/g" ${WIZARD_APP_DIR}/nginx/nginx.conf

print_info "Nginx configuration updated"

# Step 8: Set up auto-renewal
print_step "Setting up automatic certificate renewal..."
cat > /etc/cron.d/certbot-wizard << EOF
# Wizard Backend SSL Certificate Renewal
# Check twice daily for certificate renewal
0 0,12 * * * root certbot renew --quiet --no-self-upgrade --deploy-hook "docker-compose -f ${WIZARD_APP_DIR}/docker-compose.production.yml restart nginx"
EOF

print_info "Auto-renewal configured"

# Step 9: Test renewal
print_step "Testing certificate renewal..."
if certbot renew --dry-run; then
    print_info "Renewal test successful"
else
    print_warning "Renewal test failed - please check configuration"
fi

# Step 10: Update environment file
print_step "Updating environment configuration..."
if [ -f ${WIZARD_APP_DIR}/.env.production ]; then
    # Update domain in .env.production
    sed -i "s|DOMAIN=.*|DOMAIN=${DOMAIN}|g" ${WIZARD_APP_DIR}/.env.production
    sed -i "s|API_URL=.*|API_URL=https://${DOMAIN}/api|g" ${WIZARD_APP_DIR}/.env.production
    sed -i "s|FRONTEND_URL=.*|FRONTEND_URL=https://${DOMAIN}|g" ${WIZARD_APP_DIR}/.env.production
    print_info "Environment file updated"
fi

# Step 11: Start services
print_step "Starting services with SSL enabled..."
cd ${WIZARD_APP_DIR}
if [ -f "./start.sh" ]; then
    ./start.sh
else
    docker-compose -f docker-compose.production.yml up -d
fi

# Step 12: Verify SSL
print_step "Verifying SSL configuration..."
sleep 5

# Test HTTPS connection
if curl -f -s -o /dev/null -w "%{http_code}" https://${DOMAIN}/health | grep -q "200"; then
    print_info "✅ HTTPS is working!"
else
    print_warning "HTTPS test failed - please check nginx logs"
fi

# Display SSL certificate info
echo ""
print_info "SSL Certificate Information:"
echo "----------------------------"
openssl x509 -in ${NGINX_SSL_DIR}/fullchain.pem -noout -subject -dates | sed 's/^/  /'

# Display summary
echo ""
echo "================================================"
echo "   SSL Setup Complete!"
echo "================================================"
echo ""
print_info "Domain: https://${DOMAIN}"
print_info "Certificate location: ${NGINX_SSL_DIR}"
print_info "Auto-renewal: Enabled (twice daily)"
echo ""
print_info "Next steps:"
echo "  1. Update your DNS records to point to this server"
echo "  2. Test SSL at: https://www.ssllabs.com/ssltest/analyze.html?d=${DOMAIN}"
echo "  3. Monitor renewal: certbot certificates"
echo ""

# Security recommendations
print_warning "Security Recommendations:"
echo "  - Enable firewall (ufw) for ports 80 and 443 only"
echo "  - Configure CloudFlare or AWS WAF for DDoS protection"
echo "  - Set up monitoring for certificate expiration"
echo "  - Backup certificates: ${CERT_PATH}"
echo ""

# Create helper script for manual renewal
cat > ${WIZARD_APP_DIR}/renew-ssl.sh << EOF
#!/bin/bash
# Manual SSL renewal script
certbot renew --force-renewal
docker-compose -f ${WIZARD_APP_DIR}/docker-compose.production.yml restart nginx
echo "SSL certificate renewed and nginx restarted"
EOF
chmod +x ${WIZARD_APP_DIR}/renew-ssl.sh

print_info "Manual renewal script created: ${WIZARD_APP_DIR}/renew-ssl.sh"